# Generated by Django 3.1.3 on 2021-10-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('population_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='Sensor_data',
        ),
    ]
