# Generated by Django 3.1.3 on 2021-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population_tracker', '0002_auto_20211030_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
